### ISSUE TITLE
Bad calibrations on website (fixed)

### ISSUE THREAD

**Issue by tcies** [uzh-rpg/IROS2019-FPV-VIO-Competition#3]
In the heat of the website upload, we mistakenly used radtan instead of equidistant distortion in the camera calibrations. This has now been fixed. The calibrations on the website are updated.

Find below reprojection errors after IMU calibration before (left) and after (right) the fix.

# Snapdragon

## Indoor 45
![Screenshot from 2019-08-12 12-37-56](https://user-images.githubusercontent.com/4147796/62867361-65b68700-bd13-11e9-9bd5-25292f9a4d1e.png)

## Indoor forward
![Screenshot from 2019-08-12 13-38-51](https://user-images.githubusercontent.com/4147796/62867340-5afbf200-bd13-11e9-8bce-daca7439ef07.png)

## Outdoor 45
![Screenshot from 2019-08-12 14-01-09](https://user-images.githubusercontent.com/4147796/62867326-50d9f380-bd13-11e9-8618-b05aade510d7.png)

## Outdoor forward
![Screenshot from 2019-08-12 14-16-15](https://user-images.githubusercontent.com/4147796/62867309-47508b80-bd13-11e9-97ca-0a90d363cf01.png)

# DAVIS

## Indoor 45
![Screenshot from 2019-08-12 14-57-26](https://user-images.githubusercontent.com/4147796/62867436-8a126380-bd13-11e9-88af-20de0d6de8dc.png)

## Indoor forward
![Screenshot from 2019-08-12 14-58-20](https://user-images.githubusercontent.com/4147796/62867442-8d0d5400-bd13-11e9-94db-729ef0186d53.png)

## Outdoor 45
![Screenshot from 2019-08-12 14-59-11](https://user-images.githubusercontent.com/4147796/62867449-90a0db00-bd13-11e9-9988-bda4c3dbdb96.png)

## Outdoor forward
![Screenshot from 2019-08-12 14-59-55](https://user-images.githubusercontent.com/4147796/62867454-94346200-bd13-11e9-9b9c-d637b24ea3fb.png)

**Comment by VladyslavUsenko** [comment]
There is apparently a delay between camera and IMU. On the indoor sequences it is around 16ms and on outdoor sequences around 8ms. 
```
# indoors_forward
timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.0166845720919

# indoors_45
timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.0148488882666

# outdoors_forward
timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.00799924320506

# outdoors_45
timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.00863751181076
```

Do you know why this happens (why the delay changes from sequence to sequence)? Are the cameras and the IMU hardware synchronized?

**Comment by tcies** [comment]
@VladyslavUsenko we can take a closer look later this week. Technically, the sensors should be hardware synchronized. @jeffdelmerico told me that differences in estimated shift might be due to different exposure times.

**Comment by tcies** [comment]
@VladyslavUsenko Just discussed this with my colleagues and this could be quite a rabbit hole. Our current guesses:

* The hardware sync stamp would most likely be from the beginning of the exposure time (to be verified), whereas kalibr would most likely optimize for the middle of the exposure time. Auto exposure was enabled for all snapdragon datasets. If this is the case, it could be tricky to provide a very precise time shift for the datasets.
* The DVS had low-pass filtering of the IMU data enabled, and in accordance with this, we see a consistent time shift estimate of around 5ms in the calibrations. This time shift should be taken into account in the VIO.

**Comment by VladyslavUsenko** [comment]
Thanks for looking into that! I think Kalibr assumes the timestamps to be the middle of exposure. We've also got the same results with our calibration tool that definitely expects the middle of exposure timestamps. If you've recorded the exposure times for the frames you can easily fix it by adding half of the exposure time to the timestamps.
