### ISSUE TITLE
Outdoor 16 Dataset

### ISSUE THREAD

**Issue by goldbattle** [uzh-rpg/IROS2019-FPV-VIO-Competition#5]
I was looking at the [paper](http://rpg.ifi.uzh.ch/docs/ICRA19_Delmerico.pdf) and saw that figure 8 was of the "outdoor 16" dataset. I might have missed it on the website, but is this available for download? I see that the outdoor only goes up to number 10. Thanks! Really interesting dataset.

![image](https://user-images.githubusercontent.com/2222562/65286126-73c6a700-db0c-11e9-8f36-ac01c43c281b.png)

**Comment by tcies** [comment]
Unfortunately not. The results in this figure are from an earlier dataset which we chose not to release because it does not have stereo data. A dataset that should be similar might be "outdoor forward facing" 3.
