### ISSUE TITLE
Ground truth time alignment

### ISSUE THREAD

**Issue by VladyslavUsenko** [uzh-rpg/IROS2019-FPV-VIO-Competition#6]
Hi all,

I've tried to check if the GT data for the available sequences is well time aligned to the IMU data and it seems that there is a constant offset of around 100ms at least on the indoor sequences. 
**At the speeds of around 10m/s this misalignment might result in ~1m position error.**

The following plot shows the rotational velocities computed from the ground truth and the gyro measurements (indoor_forward_3_snapdragon_with_gt):
<img width="1440" alt="Screenshot 2019-09-20 at 10 02 52" src="https://user-images.githubusercontent.com/2621267/65310581-ed06de00-db8e-11e9-9cc7-c08efb88db86.png">

After running a grid search it shows the minimum at -99ms and the plot looks like this:
<img width="1440" alt="Screenshot 2019-09-20 at 10 06 13" src="https://user-images.githubusercontent.com/2621267/65310646-0dcf3380-db8f-11e9-9b90-0ea8cbeadae1.png">

This is consistent with all indoor forward sequences I've checked. Here is indoor_forward_9_snapdragon_with_gt with minimum error at -95ms
<img width="1440" alt="Screenshot 2019-09-20 at 10 07 51" src="https://user-images.githubusercontent.com/2621267/65310723-3eaf6880-db8f-11e9-86fb-9285deaa2633.png">

Do you have any ideas?

**Comment by goldbattle** [comment]
This gives me much lower error on the forward indoor datasets. Did you find any values for the indoor 45 and outdoor? I am assuming this time alignment is the same performed for the [tum-vi](https://vision.in.tum.de/data/datasets/visual-inertial-dataset#time_alignment_hand-eye_calibration_imu_axis_scaling_and_misalignment) datasets? Is this code available someplace online?

**Comment by VladyslavUsenko** [comment]
The code is here:
https://gitlab.com/VladyslavUsenko/basalt/blob/master/src/time_alignment.cpp

I run with:
```
basalt_time_alignment --dataset-path ~/Datasets/UZH/indoor_forward_3_snapdragon_with_gt --dataset-type uzh
```

**Comment by goldbattle** [comment]
Any update on this? I got the following using @VladyslavUsenko utility:
- indoor forward 7 => -0.1010683 sec offset
- indoor 45 14 => -0.1009 sec offset
- outdoor forward 3 => -0.10076554 sec offset

**Comment by supitalp** [comment]
Hello,
Thanks for reporting. We are currently investigating this, and will try to get back to you asap.

**Comment by tcies** [comment]
We are looking into this, and it should be addressed for the upcoming edition of the competition! Thank you very much for reporting!

**Comment by tcies** [comment]
So, just to clarify (as this might not have been communicated before): For the evaluation of the IROS 2019 competition, we have used a version of the ground truth that has been time-aligned as raised by this issue, see Vladyslav's analysis before and after alignment below. This ground truth will also be used for the ICRA 2020 edition of the competition.

We are now working on making sure that all ground truth files are updated according to this time offset correction. We will also double-check that this issue has not affected the shape of the ground truth. If it did, ground truths will be updated. We are also working on some other potentially useful things, but I don't want to make any promises yet.

## Ground truth used for competition evaluation

| Before fix | After fix (this one was used) |
|---|---|
| ![i4_3_before](https://user-images.githubusercontent.com/4147796/77310477-b016d200-6cfe-11ea-8dd3-ca695798fc1a.png)  |  ![i4_3_after](https://user-images.githubusercontent.com/4147796/77310493-b6a54980-6cfe-11ea-8991-6691c7e33ad6.png)  |
| ![i4_16_before](https://user-images.githubusercontent.com/4147796/77310554-ce7ccd80-6cfe-11ea-902a-3c76f37ef994.png) | ![i4_16_after](https://user-images.githubusercontent.com/4147796/77310563-d2105480-6cfe-11ea-9136-d0791e310c81.png) |
| ![if11_before](https://user-images.githubusercontent.com/4147796/77310572-d6d50880-6cfe-11ea-9a2b-3cf9212cc2bf.png) | ![if11_after](https://user-images.githubusercontent.com/4147796/77310582-db012600-6cfe-11ea-919b-9a11f9251e6b.png)  |
| ![if12_before](https://user-images.githubusercontent.com/4147796/77310591-df2d4380-6cfe-11ea-958f-550330651220.png)  |  ![if12_after](https://user-images.githubusercontent.com/4147796/77310600-e2c0ca80-6cfe-11ea-9e1b-ea95fe1483db.png) |
| ![of9before](https://user-images.githubusercontent.com/4147796/77310612-e81e1500-6cfe-11ea-80d0-4bdbaf138570.png)  | ![of9_after](https://user-images.githubusercontent.com/4147796/77310622-ec4a3280-6cfe-11ea-8b67-3a5869aea5c6.png)  |
| ![of10before](https://user-images.githubusercontent.com/4147796/77310639-f10ee680-6cfe-11ea-8c8e-7e1cf87b6b7b.png)  | ![of10after](https://user-images.githubusercontent.com/4147796/77310651-f4a26d80-6cfe-11ea-85fb-627c34c01c83.png)  |

**Comment by tcies** [comment]
This issue is now addressed, updated all ground truths: 
http://rpg.ifi.uzh.ch/uzh-fpv.html 

Thanks @VladyslavUsenko and @goldbattle for reporting!
