### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by sombitd** [uzh-rpg/IROS2019-FPV-VIO-Competition#8]
Unable to access the Bag files and the calibration files.

**Comment by supitalp** [comment]
Hello,
Looking into it right now. Will come back to you asap.
Best,
Henri

**Comment by supitalp** [comment]
Hello,
It seems the website is back up online right now. I am in contact with our techno team and they will look into the problem. Sorry for the inconvenience.

**Comment by supitalp** [comment]
Our techno team hasn't found any problems. Looks like everything has been working well in the last two days, so I'll close this issue now. Please reopen if the problem reappears.
