### ISSUE TITLE
Cannot access the datasets

### ISSUE THREAD

**Issue by juanmed** [uzh-rpg/IROS2019-FPV-VIO-Competition#9]
Hello,

I am unable to access the datasets in the github links nor directly on `http://rpg.ifi.uzh.ch/uzh-fpv.html`. Can you please confirm if the page is up/down?

Thanks,

**Comment by tcies** [comment]
This was a temporary issue with the servers of our university. Sorry for not being able to respond in time, thanks for reporting!
